; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200 ; Velocità del monitor seriale
monitor_raw = yes ; Forza il monitor a connettersi alla porta corretta
board_upload.flash_size = 2MB ; Forza PlatformIO a considerare la Flash da 2MB in fase di flash
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
lib_deps =
    https://github.com/igna09/KLineKWP1281Lib_ESP32.git
build_flags = 
    -Wno-missing-field-initializers
    -Wno-attributes

[env:KlineNode]
extends = esp32-c3-devkitm-1
board_build.cmake_extra_args = -DCARDUINO_NODE=KLINE