; PlatformIO Project Configuration File

[base_settings]
base_config = sdkconfig.defaults

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 2MB
board_build.flash_size = 2MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="${base_settings.base_config}"
build_flags = 
    -Os
    -Wno-missing-field-initializers
    -Wno-attributes
monitor_filters = esp32_exception_decoder, default
extra_scripts = pre:pass_env_to_cmake.py
build_unflags = -fuse-cxa-atexit
; lib_deps =
;     https://github.com/esp-idf-lib/esp_idf_lib_helpers.git
;     https://github.com/esp-idf-lib/i2cdev.git ;find solution to import it dinamically
; Specifica il file di configurazione delle partizioni
board_build.partitions = partitions_2mb.csv

[env:BaseNode]
extends = env

[env:KlineNode]
extends = env
lib_deps =
    ${env.lib_deps}
    https://github.com/igna09/KLineKWP1281Lib_ESP32.git

[env:UdpAp]
extends = env

[env:MainNode]
extends = env
lib_deps =
    ${env.lib_deps}
    ; https://github.com/esp-idf-lib/aht.git
; board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="${base_settings.base_config};sdkconfig.no_logs"
    
[env:MediaNode]
extends = env
; lib_deps =
;     https://github.com/esp-idf-lib/encoder.git

[env:CanTest]
extends = env

[env:CanTestSender]
extends = env

[env:CanTestReceiver]
extends = env