; PlatformIO Project Configuration File

[env:base_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 2MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
; Forza la compilazione con i simboli di debug (-g3) per l'exception decoder
build_type = debug
build_flags = 
    -g3
    -Wno-missing-field-initializers
    -Wno-attributes

[env:KlineNode]
extends = env:base_c3
lib_deps =
    https://github.com/igna09/KLineKWP1281Lib_ESP32.git
board_build.cmake_extra_args = -DCARDUINO_NODE=KLINE
; Filtri del monitor: esp32_exception_decoder serve a tradurre i crash, 
; default serve ad abilitare i colori dei log ESP-IDF (I, W, E)
monitor_filters = esp32_exception_decoder, default

[env:UdpAp]
extends = env:base_c3
board_build.cmake_extra_args = -DCARDUINO_NODE=UDP_AP