#!/usr/bin/env python3

# install dependencies:
# python3 -m pip install gitpython

import re
import subprocess
from git import Repo

def increase_version(filename, define_name):
    """
    Updates a define in a C/C++ header file.

    Args:
        filename: The path to the header file.
        define_name: The name of the define to update.
    """

    with open(filename, 'r') as f:
        content = f.read()

    # Find the existing define line
    match = re.search(r'^#define\s+' + define_name + r'\s+(.+)$', content, re.MULTILINE)
    if match:
        # Extract the current value
        current_value = int(match.group(1))
        # Increment the value
        new_value = current_value + 1
        # Replace the existing value
        content = re.sub(r'^#define\s+' + define_name + r'\s+(.+)$', '#define ' + define_name + ' ' + str(new_value), content, 1, re.MULTILINE)
    else:
        # Add the define if it doesn't exist
        content += '\n#define ' + define_name + ' 1'

    with open(filename, 'w') as f:
        f.write(content)

    repo = Repo('c:\\Users\\I.Abbate\\Documents\\PlatformioProjects\\carduino_arduino')
    repo.index.add('src\\shared\\SharedDefinitions.h')

def main():
    """
    Main function for the pre-commit hook.
    """

    filename = 'c:\\Users\\I.Abbate\\Documents\\PlatformioProjects\\carduino_arduino\\src\\shared\\SharedDefinitions.h'
    define_name = '__VERSION__'

    increase_version(filename, define_name)

    # Print a success message
    print(f'Updated define {define_name} in SharedDefinitions.h')

if __name__ == '__main__':
    main()