#define FOREACH_CATEGORY(CATEGORY) \
        CATEGORY(CAR_STATUS)   \
        CATEGORY(READ_SETTING)  \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum Category {
    FOREACH_CATEGORY(GENERATE_ENUM)
};

static const char *CATEGORY_STRING[] = {
    FOREACH_CATEGORY(GENERATE_STRING)
};