#define DEFAULT_CAN_RX_PIN GPIO_NUM_20
#define DEFAULT_CAN_TX_PIN GPIO_NUM_21

#define DEFAULT_I2C_SCL_PIN GPIO_NUM_7
#define DEFAULT_I2C_SDA_PIN GPIO_NUM_6

#define UDP_LOG_PORT            3333
#define UDP_LOG_WIFI_SSID       "CARDUINO_DEBUG_NET"
#define UDP_LOG_WIFI_PASSWORD   "AutomotiveSec2026"