#pragma once

#define FOREACH_CARSTATUS_CANBUS_MESSAGE_TYPE(ACTION) \
        ACTION(INT)   \
        ACTION(FLOAT)   \
        ACTION(STRING)   \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum CarstatusCanbusMessageType {
    FOREACH_CARSTATUS_CANBUS_MESSAGE_TYPE(GENERATE_ENUM)
};

static const char *CARSTATUS_CANBUS_MESSAGE_TYPE_STRING[] = {
    FOREACH_CARSTATUS_CANBUS_MESSAGE_TYPE(GENERATE_STRING)
};
